/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tracker.api.thrift.web;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class LogFilter implements org.apache.thrift.TBase<LogFilter, LogFilter._Fields>, java.io.Serializable, Cloneable, Comparable<LogFilter> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LogFilter");

  private static final org.apache.thrift.protocol.TField VISIT_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("visitType", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField IS_CALL_SELOG_FIELD_DESC = new org.apache.thrift.protocol.TField("isCallSELog", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new LogFilterStandardSchemeFactory());
    schemes.put(TupleScheme.class, new LogFilterTupleSchemeFactory());
  }

  public int visitType; // optional
  public int isCallSELog; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VISIT_TYPE((short)1, "visitType"),
    IS_CALL_SELOG((short)2, "isCallSELog");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VISIT_TYPE
          return VISIT_TYPE;
        case 2: // IS_CALL_SELOG
          return IS_CALL_SELOG;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VISITTYPE_ISSET_ID = 0;
  private static final int __ISCALLSELOG_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.VISIT_TYPE,_Fields.IS_CALL_SELOG};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VISIT_TYPE, new org.apache.thrift.meta_data.FieldMetaData("visitType", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.IS_CALL_SELOG, new org.apache.thrift.meta_data.FieldMetaData("isCallSELog", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LogFilter.class, metaDataMap);
  }

  public LogFilter() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LogFilter(LogFilter other) {
    __isset_bitfield = other.__isset_bitfield;
    this.visitType = other.visitType;
    this.isCallSELog = other.isCallSELog;
  }

  public LogFilter deepCopy() {
    return new LogFilter(this);
  }

  @Override
  public void clear() {
    setVisitTypeIsSet(false);
    this.visitType = 0;
    setIsCallSELogIsSet(false);
    this.isCallSELog = 0;
  }

  public int getVisitType() {
    return this.visitType;
  }

  public LogFilter setVisitType(int visitType) {
    this.visitType = visitType;
    setVisitTypeIsSet(true);
    return this;
  }

  public void unsetVisitType() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __VISITTYPE_ISSET_ID);
  }

  /** Returns true if field visitType is set (has been assigned a value) and false otherwise */
  public boolean isSetVisitType() {
    return EncodingUtils.testBit(__isset_bitfield, __VISITTYPE_ISSET_ID);
  }

  public void setVisitTypeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __VISITTYPE_ISSET_ID, value);
  }

  public int getIsCallSELog() {
    return this.isCallSELog;
  }

  public LogFilter setIsCallSELog(int isCallSELog) {
    this.isCallSELog = isCallSELog;
    setIsCallSELogIsSet(true);
    return this;
  }

  public void unsetIsCallSELog() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ISCALLSELOG_ISSET_ID);
  }

  /** Returns true if field isCallSELog is set (has been assigned a value) and false otherwise */
  public boolean isSetIsCallSELog() {
    return EncodingUtils.testBit(__isset_bitfield, __ISCALLSELOG_ISSET_ID);
  }

  public void setIsCallSELogIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ISCALLSELOG_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case VISIT_TYPE:
      if (value == null) {
        unsetVisitType();
      } else {
        setVisitType((Integer)value);
      }
      break;

    case IS_CALL_SELOG:
      if (value == null) {
        unsetIsCallSELog();
      } else {
        setIsCallSELog((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case VISIT_TYPE:
      return Integer.valueOf(getVisitType());

    case IS_CALL_SELOG:
      return Integer.valueOf(getIsCallSELog());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case VISIT_TYPE:
      return isSetVisitType();
    case IS_CALL_SELOG:
      return isSetIsCallSELog();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof LogFilter)
      return this.equals((LogFilter)that);
    return false;
  }

  public boolean equals(LogFilter that) {
    if (that == null)
      return false;

    boolean this_present_visitType = true && this.isSetVisitType();
    boolean that_present_visitType = true && that.isSetVisitType();
    if (this_present_visitType || that_present_visitType) {
      if (!(this_present_visitType && that_present_visitType))
        return false;
      if (this.visitType != that.visitType)
        return false;
    }

    boolean this_present_isCallSELog = true && this.isSetIsCallSELog();
    boolean that_present_isCallSELog = true && that.isSetIsCallSELog();
    if (this_present_isCallSELog || that_present_isCallSELog) {
      if (!(this_present_isCallSELog && that_present_isCallSELog))
        return false;
      if (this.isCallSELog != that.isCallSELog)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(LogFilter other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetVisitType()).compareTo(other.isSetVisitType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVisitType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.visitType, other.visitType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIsCallSELog()).compareTo(other.isSetIsCallSELog());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsCallSELog()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isCallSELog, other.isCallSELog);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("LogFilter(");
    boolean first = true;

    if (isSetVisitType()) {
      sb.append("visitType:");
      sb.append(this.visitType);
      first = false;
    }
    if (isSetIsCallSELog()) {
      if (!first) sb.append(", ");
      sb.append("isCallSELog:");
      sb.append(this.isCallSELog);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LogFilterStandardSchemeFactory implements SchemeFactory {
    public LogFilterStandardScheme getScheme() {
      return new LogFilterStandardScheme();
    }
  }

  private static class LogFilterStandardScheme extends StandardScheme<LogFilter> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, LogFilter struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VISIT_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.visitType = iprot.readI32();
              struct.setVisitTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // IS_CALL_SELOG
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.isCallSELog = iprot.readI32();
              struct.setIsCallSELogIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, LogFilter struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetVisitType()) {
        oprot.writeFieldBegin(VISIT_TYPE_FIELD_DESC);
        oprot.writeI32(struct.visitType);
        oprot.writeFieldEnd();
      }
      if (struct.isSetIsCallSELog()) {
        oprot.writeFieldBegin(IS_CALL_SELOG_FIELD_DESC);
        oprot.writeI32(struct.isCallSELog);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LogFilterTupleSchemeFactory implements SchemeFactory {
    public LogFilterTupleScheme getScheme() {
      return new LogFilterTupleScheme();
    }
  }

  private static class LogFilterTupleScheme extends TupleScheme<LogFilter> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LogFilter struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetVisitType()) {
        optionals.set(0);
      }
      if (struct.isSetIsCallSELog()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetVisitType()) {
        oprot.writeI32(struct.visitType);
      }
      if (struct.isSetIsCallSELog()) {
        oprot.writeI32(struct.isCallSELog);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LogFilter struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.visitType = iprot.readI32();
        struct.setVisitTypeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.isCallSELog = iprot.readI32();
        struct.setIsCallSELogIsSet(true);
      }
    }
  }

}

