/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tracker.api.thrift.web;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 来源类型过滤
 */
public class ReferrerFilter implements org.apache.thrift.TBase<ReferrerFilter, ReferrerFilter._Fields>, java.io.Serializable, Cloneable, Comparable<ReferrerFilter> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ReferrerFilter");

  private static final org.apache.thrift.protocol.TField REF_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("refType", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField SE_DOMAIN_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("seDomainId", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ReferrerFilterStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ReferrerFilterTupleSchemeFactory());
  }

  public int refType; // optional
  public int seDomainId; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    REF_TYPE((short)1, "refType"),
    SE_DOMAIN_ID((short)2, "seDomainId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // REF_TYPE
          return REF_TYPE;
        case 2: // SE_DOMAIN_ID
          return SE_DOMAIN_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __REFTYPE_ISSET_ID = 0;
  private static final int __SEDOMAINID_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.REF_TYPE,_Fields.SE_DOMAIN_ID};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.REF_TYPE, new org.apache.thrift.meta_data.FieldMetaData("refType", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SE_DOMAIN_ID, new org.apache.thrift.meta_data.FieldMetaData("seDomainId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ReferrerFilter.class, metaDataMap);
  }

  public ReferrerFilter() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ReferrerFilter(ReferrerFilter other) {
    __isset_bitfield = other.__isset_bitfield;
    this.refType = other.refType;
    this.seDomainId = other.seDomainId;
  }

  public ReferrerFilter deepCopy() {
    return new ReferrerFilter(this);
  }

  @Override
  public void clear() {
    setRefTypeIsSet(false);
    this.refType = 0;
    setSeDomainIdIsSet(false);
    this.seDomainId = 0;
  }

  public int getRefType() {
    return this.refType;
  }

  public ReferrerFilter setRefType(int refType) {
    this.refType = refType;
    setRefTypeIsSet(true);
    return this;
  }

  public void unsetRefType() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __REFTYPE_ISSET_ID);
  }

  /** Returns true if field refType is set (has been assigned a value) and false otherwise */
  public boolean isSetRefType() {
    return EncodingUtils.testBit(__isset_bitfield, __REFTYPE_ISSET_ID);
  }

  public void setRefTypeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __REFTYPE_ISSET_ID, value);
  }

  public int getSeDomainId() {
    return this.seDomainId;
  }

  public ReferrerFilter setSeDomainId(int seDomainId) {
    this.seDomainId = seDomainId;
    setSeDomainIdIsSet(true);
    return this;
  }

  public void unsetSeDomainId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SEDOMAINID_ISSET_ID);
  }

  /** Returns true if field seDomainId is set (has been assigned a value) and false otherwise */
  public boolean isSetSeDomainId() {
    return EncodingUtils.testBit(__isset_bitfield, __SEDOMAINID_ISSET_ID);
  }

  public void setSeDomainIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SEDOMAINID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case REF_TYPE:
      if (value == null) {
        unsetRefType();
      } else {
        setRefType((Integer)value);
      }
      break;

    case SE_DOMAIN_ID:
      if (value == null) {
        unsetSeDomainId();
      } else {
        setSeDomainId((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case REF_TYPE:
      return Integer.valueOf(getRefType());

    case SE_DOMAIN_ID:
      return Integer.valueOf(getSeDomainId());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case REF_TYPE:
      return isSetRefType();
    case SE_DOMAIN_ID:
      return isSetSeDomainId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ReferrerFilter)
      return this.equals((ReferrerFilter)that);
    return false;
  }

  public boolean equals(ReferrerFilter that) {
    if (that == null)
      return false;

    boolean this_present_refType = true && this.isSetRefType();
    boolean that_present_refType = true && that.isSetRefType();
    if (this_present_refType || that_present_refType) {
      if (!(this_present_refType && that_present_refType))
        return false;
      if (this.refType != that.refType)
        return false;
    }

    boolean this_present_seDomainId = true && this.isSetSeDomainId();
    boolean that_present_seDomainId = true && that.isSetSeDomainId();
    if (this_present_seDomainId || that_present_seDomainId) {
      if (!(this_present_seDomainId && that_present_seDomainId))
        return false;
      if (this.seDomainId != that.seDomainId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ReferrerFilter other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetRefType()).compareTo(other.isSetRefType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRefType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.refType, other.refType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSeDomainId()).compareTo(other.isSetSeDomainId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSeDomainId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.seDomainId, other.seDomainId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ReferrerFilter(");
    boolean first = true;

    if (isSetRefType()) {
      sb.append("refType:");
      sb.append(this.refType);
      first = false;
    }
    if (isSetSeDomainId()) {
      if (!first) sb.append(", ");
      sb.append("seDomainId:");
      sb.append(this.seDomainId);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ReferrerFilterStandardSchemeFactory implements SchemeFactory {
    public ReferrerFilterStandardScheme getScheme() {
      return new ReferrerFilterStandardScheme();
    }
  }

  private static class ReferrerFilterStandardScheme extends StandardScheme<ReferrerFilter> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ReferrerFilter struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // REF_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.refType = iprot.readI32();
              struct.setRefTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SE_DOMAIN_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.seDomainId = iprot.readI32();
              struct.setSeDomainIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ReferrerFilter struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetRefType()) {
        oprot.writeFieldBegin(REF_TYPE_FIELD_DESC);
        oprot.writeI32(struct.refType);
        oprot.writeFieldEnd();
      }
      if (struct.isSetSeDomainId()) {
        oprot.writeFieldBegin(SE_DOMAIN_ID_FIELD_DESC);
        oprot.writeI32(struct.seDomainId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ReferrerFilterTupleSchemeFactory implements SchemeFactory {
    public ReferrerFilterTupleScheme getScheme() {
      return new ReferrerFilterTupleScheme();
    }
  }

  private static class ReferrerFilterTupleScheme extends TupleScheme<ReferrerFilter> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ReferrerFilter struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetRefType()) {
        optionals.set(0);
      }
      if (struct.isSetSeDomainId()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetRefType()) {
        oprot.writeI32(struct.refType);
      }
      if (struct.isSetSeDomainId()) {
        oprot.writeI32(struct.seDomainId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ReferrerFilter struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.refType = iprot.readI32();
        struct.setRefTypeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.seDomainId = iprot.readI32();
        struct.setSeDomainIdIsSet(true);
      }
    }
  }

}

