/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tracker.api.thrift.web;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 访客类型:新访客(1)、老访客(2)
 */
public class UserFilter implements org.apache.thrift.TBase<UserFilter, UserFilter._Fields>, java.io.Serializable, Cloneable, Comparable<UserFilter> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserFilter");

  private static final org.apache.thrift.protocol.TField VISITOR_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("visitorType", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField USER_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("userType", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("userId", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField COOKIE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("cookieId", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField IP_FIELD_DESC = new org.apache.thrift.protocol.TField("ip", org.apache.thrift.protocol.TType.STRING, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new UserFilterStandardSchemeFactory());
    schemes.put(TupleScheme.class, new UserFilterTupleSchemeFactory());
  }

  public int visitorType; // optional
  public int userType; // optional
  public String userId; // optional
  public String cookieId; // optional
  public String ip; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VISITOR_TYPE((short)1, "visitorType"),
    USER_TYPE((short)2, "userType"),
    USER_ID((short)3, "userId"),
    COOKIE_ID((short)4, "cookieId"),
    IP((short)5, "ip");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VISITOR_TYPE
          return VISITOR_TYPE;
        case 2: // USER_TYPE
          return USER_TYPE;
        case 3: // USER_ID
          return USER_ID;
        case 4: // COOKIE_ID
          return COOKIE_ID;
        case 5: // IP
          return IP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VISITORTYPE_ISSET_ID = 0;
  private static final int __USERTYPE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.VISITOR_TYPE,_Fields.USER_TYPE,_Fields.USER_ID,_Fields.COOKIE_ID,_Fields.IP};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VISITOR_TYPE, new org.apache.thrift.meta_data.FieldMetaData("visitorType", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.USER_TYPE, new org.apache.thrift.meta_data.FieldMetaData("userType", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.USER_ID, new org.apache.thrift.meta_data.FieldMetaData("userId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.COOKIE_ID, new org.apache.thrift.meta_data.FieldMetaData("cookieId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IP, new org.apache.thrift.meta_data.FieldMetaData("ip", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserFilter.class, metaDataMap);
  }

  public UserFilter() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UserFilter(UserFilter other) {
    __isset_bitfield = other.__isset_bitfield;
    this.visitorType = other.visitorType;
    this.userType = other.userType;
    if (other.isSetUserId()) {
      this.userId = other.userId;
    }
    if (other.isSetCookieId()) {
      this.cookieId = other.cookieId;
    }
    if (other.isSetIp()) {
      this.ip = other.ip;
    }
  }

  public UserFilter deepCopy() {
    return new UserFilter(this);
  }

  @Override
  public void clear() {
    setVisitorTypeIsSet(false);
    this.visitorType = 0;
    setUserTypeIsSet(false);
    this.userType = 0;
    this.userId = null;
    this.cookieId = null;
    this.ip = null;
  }

  public int getVisitorType() {
    return this.visitorType;
  }

  public UserFilter setVisitorType(int visitorType) {
    this.visitorType = visitorType;
    setVisitorTypeIsSet(true);
    return this;
  }

  public void unsetVisitorType() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __VISITORTYPE_ISSET_ID);
  }

  /** Returns true if field visitorType is set (has been assigned a value) and false otherwise */
  public boolean isSetVisitorType() {
    return EncodingUtils.testBit(__isset_bitfield, __VISITORTYPE_ISSET_ID);
  }

  public void setVisitorTypeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __VISITORTYPE_ISSET_ID, value);
  }

  public int getUserType() {
    return this.userType;
  }

  public UserFilter setUserType(int userType) {
    this.userType = userType;
    setUserTypeIsSet(true);
    return this;
  }

  public void unsetUserType() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __USERTYPE_ISSET_ID);
  }

  /** Returns true if field userType is set (has been assigned a value) and false otherwise */
  public boolean isSetUserType() {
    return EncodingUtils.testBit(__isset_bitfield, __USERTYPE_ISSET_ID);
  }

  public void setUserTypeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __USERTYPE_ISSET_ID, value);
  }

  public String getUserId() {
    return this.userId;
  }

  public UserFilter setUserId(String userId) {
    this.userId = userId;
    return this;
  }

  public void unsetUserId() {
    this.userId = null;
  }

  /** Returns true if field userId is set (has been assigned a value) and false otherwise */
  public boolean isSetUserId() {
    return this.userId != null;
  }

  public void setUserIdIsSet(boolean value) {
    if (!value) {
      this.userId = null;
    }
  }

  public String getCookieId() {
    return this.cookieId;
  }

  public UserFilter setCookieId(String cookieId) {
    this.cookieId = cookieId;
    return this;
  }

  public void unsetCookieId() {
    this.cookieId = null;
  }

  /** Returns true if field cookieId is set (has been assigned a value) and false otherwise */
  public boolean isSetCookieId() {
    return this.cookieId != null;
  }

  public void setCookieIdIsSet(boolean value) {
    if (!value) {
      this.cookieId = null;
    }
  }

  public String getIp() {
    return this.ip;
  }

  public UserFilter setIp(String ip) {
    this.ip = ip;
    return this;
  }

  public void unsetIp() {
    this.ip = null;
  }

  /** Returns true if field ip is set (has been assigned a value) and false otherwise */
  public boolean isSetIp() {
    return this.ip != null;
  }

  public void setIpIsSet(boolean value) {
    if (!value) {
      this.ip = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case VISITOR_TYPE:
      if (value == null) {
        unsetVisitorType();
      } else {
        setVisitorType((Integer)value);
      }
      break;

    case USER_TYPE:
      if (value == null) {
        unsetUserType();
      } else {
        setUserType((Integer)value);
      }
      break;

    case USER_ID:
      if (value == null) {
        unsetUserId();
      } else {
        setUserId((String)value);
      }
      break;

    case COOKIE_ID:
      if (value == null) {
        unsetCookieId();
      } else {
        setCookieId((String)value);
      }
      break;

    case IP:
      if (value == null) {
        unsetIp();
      } else {
        setIp((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case VISITOR_TYPE:
      return Integer.valueOf(getVisitorType());

    case USER_TYPE:
      return Integer.valueOf(getUserType());

    case USER_ID:
      return getUserId();

    case COOKIE_ID:
      return getCookieId();

    case IP:
      return getIp();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case VISITOR_TYPE:
      return isSetVisitorType();
    case USER_TYPE:
      return isSetUserType();
    case USER_ID:
      return isSetUserId();
    case COOKIE_ID:
      return isSetCookieId();
    case IP:
      return isSetIp();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof UserFilter)
      return this.equals((UserFilter)that);
    return false;
  }

  public boolean equals(UserFilter that) {
    if (that == null)
      return false;

    boolean this_present_visitorType = true && this.isSetVisitorType();
    boolean that_present_visitorType = true && that.isSetVisitorType();
    if (this_present_visitorType || that_present_visitorType) {
      if (!(this_present_visitorType && that_present_visitorType))
        return false;
      if (this.visitorType != that.visitorType)
        return false;
    }

    boolean this_present_userType = true && this.isSetUserType();
    boolean that_present_userType = true && that.isSetUserType();
    if (this_present_userType || that_present_userType) {
      if (!(this_present_userType && that_present_userType))
        return false;
      if (this.userType != that.userType)
        return false;
    }

    boolean this_present_userId = true && this.isSetUserId();
    boolean that_present_userId = true && that.isSetUserId();
    if (this_present_userId || that_present_userId) {
      if (!(this_present_userId && that_present_userId))
        return false;
      if (!this.userId.equals(that.userId))
        return false;
    }

    boolean this_present_cookieId = true && this.isSetCookieId();
    boolean that_present_cookieId = true && that.isSetCookieId();
    if (this_present_cookieId || that_present_cookieId) {
      if (!(this_present_cookieId && that_present_cookieId))
        return false;
      if (!this.cookieId.equals(that.cookieId))
        return false;
    }

    boolean this_present_ip = true && this.isSetIp();
    boolean that_present_ip = true && that.isSetIp();
    if (this_present_ip || that_present_ip) {
      if (!(this_present_ip && that_present_ip))
        return false;
      if (!this.ip.equals(that.ip))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(UserFilter other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetVisitorType()).compareTo(other.isSetVisitorType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVisitorType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.visitorType, other.visitorType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUserType()).compareTo(other.isSetUserType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userType, other.userType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUserId()).compareTo(other.isSetUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userId, other.userId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCookieId()).compareTo(other.isSetCookieId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCookieId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cookieId, other.cookieId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIp()).compareTo(other.isSetIp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ip, other.ip);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UserFilter(");
    boolean first = true;

    if (isSetVisitorType()) {
      sb.append("visitorType:");
      sb.append(this.visitorType);
      first = false;
    }
    if (isSetUserType()) {
      if (!first) sb.append(", ");
      sb.append("userType:");
      sb.append(this.userType);
      first = false;
    }
    if (isSetUserId()) {
      if (!first) sb.append(", ");
      sb.append("userId:");
      if (this.userId == null) {
        sb.append("null");
      } else {
        sb.append(this.userId);
      }
      first = false;
    }
    if (isSetCookieId()) {
      if (!first) sb.append(", ");
      sb.append("cookieId:");
      if (this.cookieId == null) {
        sb.append("null");
      } else {
        sb.append(this.cookieId);
      }
      first = false;
    }
    if (isSetIp()) {
      if (!first) sb.append(", ");
      sb.append("ip:");
      if (this.ip == null) {
        sb.append("null");
      } else {
        sb.append(this.ip);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UserFilterStandardSchemeFactory implements SchemeFactory {
    public UserFilterStandardScheme getScheme() {
      return new UserFilterStandardScheme();
    }
  }

  private static class UserFilterStandardScheme extends StandardScheme<UserFilter> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UserFilter struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VISITOR_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.visitorType = iprot.readI32();
              struct.setVisitorTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // USER_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.userType = iprot.readI32();
              struct.setUserTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.userId = iprot.readString();
              struct.setUserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // COOKIE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.cookieId = iprot.readString();
              struct.setCookieIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // IP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ip = iprot.readString();
              struct.setIpIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UserFilter struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetVisitorType()) {
        oprot.writeFieldBegin(VISITOR_TYPE_FIELD_DESC);
        oprot.writeI32(struct.visitorType);
        oprot.writeFieldEnd();
      }
      if (struct.isSetUserType()) {
        oprot.writeFieldBegin(USER_TYPE_FIELD_DESC);
        oprot.writeI32(struct.userType);
        oprot.writeFieldEnd();
      }
      if (struct.userId != null) {
        if (struct.isSetUserId()) {
          oprot.writeFieldBegin(USER_ID_FIELD_DESC);
          oprot.writeString(struct.userId);
          oprot.writeFieldEnd();
        }
      }
      if (struct.cookieId != null) {
        if (struct.isSetCookieId()) {
          oprot.writeFieldBegin(COOKIE_ID_FIELD_DESC);
          oprot.writeString(struct.cookieId);
          oprot.writeFieldEnd();
        }
      }
      if (struct.ip != null) {
        if (struct.isSetIp()) {
          oprot.writeFieldBegin(IP_FIELD_DESC);
          oprot.writeString(struct.ip);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UserFilterTupleSchemeFactory implements SchemeFactory {
    public UserFilterTupleScheme getScheme() {
      return new UserFilterTupleScheme();
    }
  }

  private static class UserFilterTupleScheme extends TupleScheme<UserFilter> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UserFilter struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetVisitorType()) {
        optionals.set(0);
      }
      if (struct.isSetUserType()) {
        optionals.set(1);
      }
      if (struct.isSetUserId()) {
        optionals.set(2);
      }
      if (struct.isSetCookieId()) {
        optionals.set(3);
      }
      if (struct.isSetIp()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetVisitorType()) {
        oprot.writeI32(struct.visitorType);
      }
      if (struct.isSetUserType()) {
        oprot.writeI32(struct.userType);
      }
      if (struct.isSetUserId()) {
        oprot.writeString(struct.userId);
      }
      if (struct.isSetCookieId()) {
        oprot.writeString(struct.cookieId);
      }
      if (struct.isSetIp()) {
        oprot.writeString(struct.ip);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UserFilter struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.visitorType = iprot.readI32();
        struct.setVisitorTypeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.userType = iprot.readI32();
        struct.setUserTypeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.userId = iprot.readString();
        struct.setUserIdIsSet(true);
      }
      if (incoming.get(3)) {
        struct.cookieId = iprot.readString();
        struct.setCookieIdIsSet(true);
      }
      if (incoming.get(4)) {
        struct.ip = iprot.readString();
        struct.setIpIsSet(true);
      }
    }
  }

}

