/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tracker.api.thrift.web;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 用户历史记录集合
 */
public class UserLogResult implements org.apache.thrift.TBase<UserLogResult, UserLogResult._Fields>, java.io.Serializable, Cloneable, Comparable<UserLogResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserLogResult");

  private static final org.apache.thrift.protocol.TField USER_LOG_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("userLogList", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField TOTAL_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("totalCount", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new UserLogResultStandardSchemeFactory());
    schemes.put(TupleScheme.class, new UserLogResultTupleSchemeFactory());
  }

  public List<UserLog> userLogList; // required
  public int totalCount; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    USER_LOG_LIST((short)1, "userLogList"),
    TOTAL_COUNT((short)2, "totalCount");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER_LOG_LIST
          return USER_LOG_LIST;
        case 2: // TOTAL_COUNT
          return TOTAL_COUNT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TOTALCOUNT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER_LOG_LIST, new org.apache.thrift.meta_data.FieldMetaData("userLogList", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, UserLog.class))));
    tmpMap.put(_Fields.TOTAL_COUNT, new org.apache.thrift.meta_data.FieldMetaData("totalCount", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserLogResult.class, metaDataMap);
  }

  public UserLogResult() {
  }

  public UserLogResult(
    List<UserLog> userLogList,
    int totalCount)
  {
    this();
    this.userLogList = userLogList;
    this.totalCount = totalCount;
    setTotalCountIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UserLogResult(UserLogResult other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetUserLogList()) {
      List<UserLog> __this__userLogList = new ArrayList<UserLog>(other.userLogList.size());
      for (UserLog other_element : other.userLogList) {
        __this__userLogList.add(new UserLog(other_element));
      }
      this.userLogList = __this__userLogList;
    }
    this.totalCount = other.totalCount;
  }

  public UserLogResult deepCopy() {
    return new UserLogResult(this);
  }

  @Override
  public void clear() {
    this.userLogList = null;
    setTotalCountIsSet(false);
    this.totalCount = 0;
  }

  public int getUserLogListSize() {
    return (this.userLogList == null) ? 0 : this.userLogList.size();
  }

  public java.util.Iterator<UserLog> getUserLogListIterator() {
    return (this.userLogList == null) ? null : this.userLogList.iterator();
  }

  public void addToUserLogList(UserLog elem) {
    if (this.userLogList == null) {
      this.userLogList = new ArrayList<UserLog>();
    }
    this.userLogList.add(elem);
  }

  public List<UserLog> getUserLogList() {
    return this.userLogList;
  }

  public UserLogResult setUserLogList(List<UserLog> userLogList) {
    this.userLogList = userLogList;
    return this;
  }

  public void unsetUserLogList() {
    this.userLogList = null;
  }

  /** Returns true if field userLogList is set (has been assigned a value) and false otherwise */
  public boolean isSetUserLogList() {
    return this.userLogList != null;
  }

  public void setUserLogListIsSet(boolean value) {
    if (!value) {
      this.userLogList = null;
    }
  }

  public int getTotalCount() {
    return this.totalCount;
  }

  public UserLogResult setTotalCount(int totalCount) {
    this.totalCount = totalCount;
    setTotalCountIsSet(true);
    return this;
  }

  public void unsetTotalCount() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TOTALCOUNT_ISSET_ID);
  }

  /** Returns true if field totalCount is set (has been assigned a value) and false otherwise */
  public boolean isSetTotalCount() {
    return EncodingUtils.testBit(__isset_bitfield, __TOTALCOUNT_ISSET_ID);
  }

  public void setTotalCountIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TOTALCOUNT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case USER_LOG_LIST:
      if (value == null) {
        unsetUserLogList();
      } else {
        setUserLogList((List<UserLog>)value);
      }
      break;

    case TOTAL_COUNT:
      if (value == null) {
        unsetTotalCount();
      } else {
        setTotalCount((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case USER_LOG_LIST:
      return getUserLogList();

    case TOTAL_COUNT:
      return Integer.valueOf(getTotalCount());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case USER_LOG_LIST:
      return isSetUserLogList();
    case TOTAL_COUNT:
      return isSetTotalCount();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof UserLogResult)
      return this.equals((UserLogResult)that);
    return false;
  }

  public boolean equals(UserLogResult that) {
    if (that == null)
      return false;

    boolean this_present_userLogList = true && this.isSetUserLogList();
    boolean that_present_userLogList = true && that.isSetUserLogList();
    if (this_present_userLogList || that_present_userLogList) {
      if (!(this_present_userLogList && that_present_userLogList))
        return false;
      if (!this.userLogList.equals(that.userLogList))
        return false;
    }

    boolean this_present_totalCount = true;
    boolean that_present_totalCount = true;
    if (this_present_totalCount || that_present_totalCount) {
      if (!(this_present_totalCount && that_present_totalCount))
        return false;
      if (this.totalCount != that.totalCount)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(UserLogResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetUserLogList()).compareTo(other.isSetUserLogList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserLogList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userLogList, other.userLogList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTotalCount()).compareTo(other.isSetTotalCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTotalCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.totalCount, other.totalCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UserLogResult(");
    boolean first = true;

    sb.append("userLogList:");
    if (this.userLogList == null) {
      sb.append("null");
    } else {
      sb.append(this.userLogList);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("totalCount:");
    sb.append(this.totalCount);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (userLogList == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'userLogList' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'totalCount' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UserLogResultStandardSchemeFactory implements SchemeFactory {
    public UserLogResultStandardScheme getScheme() {
      return new UserLogResultStandardScheme();
    }
  }

  private static class UserLogResultStandardScheme extends StandardScheme<UserLogResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UserLogResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // USER_LOG_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.userLogList = new ArrayList<UserLog>(_list8.size);
                for (int _i9 = 0; _i9 < _list8.size; ++_i9)
                {
                  UserLog _elem10;
                  _elem10 = new UserLog();
                  _elem10.read(iprot);
                  struct.userLogList.add(_elem10);
                }
                iprot.readListEnd();
              }
              struct.setUserLogListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TOTAL_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.totalCount = iprot.readI32();
              struct.setTotalCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetTotalCount()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'totalCount' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UserLogResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.userLogList != null) {
        oprot.writeFieldBegin(USER_LOG_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.userLogList.size()));
          for (UserLog _iter11 : struct.userLogList)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TOTAL_COUNT_FIELD_DESC);
      oprot.writeI32(struct.totalCount);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UserLogResultTupleSchemeFactory implements SchemeFactory {
    public UserLogResultTupleScheme getScheme() {
      return new UserLogResultTupleScheme();
    }
  }

  private static class UserLogResultTupleScheme extends TupleScheme<UserLogResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UserLogResult struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.userLogList.size());
        for (UserLog _iter12 : struct.userLogList)
        {
          _iter12.write(oprot);
        }
      }
      oprot.writeI32(struct.totalCount);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UserLogResult struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.userLogList = new ArrayList<UserLog>(_list13.size);
        for (int _i14 = 0; _i14 < _list13.size; ++_i14)
        {
          UserLog _elem15;
          _elem15 = new UserLog();
          _elem15.read(iprot);
          struct.userLogList.add(_elem15);
        }
      }
      struct.setUserLogListIsSet(true);
      struct.totalCount = iprot.readI32();
      struct.setTotalCountIsSet(true);
    }
  }

}

