/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tracker.api.thrift.search;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SearchEngineParam implements org.apache.thrift.TBase<SearchEngineParam, SearchEngineParam._Fields>, java.io.Serializable, Cloneable, Comparable<SearchEngineParam> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SearchEngineParam");

  private static final org.apache.thrift.protocol.TField SEARCH_ENGINE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("searchEngineId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField SEARCH_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("searchType", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SearchEngineParamStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SearchEngineParamTupleSchemeFactory());
  }

  public int searchEngineId; // optional
  public int searchType; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SEARCH_ENGINE_ID((short)1, "searchEngineId"),
    SEARCH_TYPE((short)2, "searchType");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SEARCH_ENGINE_ID
          return SEARCH_ENGINE_ID;
        case 2: // SEARCH_TYPE
          return SEARCH_TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SEARCHENGINEID_ISSET_ID = 0;
  private static final int __SEARCHTYPE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.SEARCH_ENGINE_ID,_Fields.SEARCH_TYPE};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SEARCH_ENGINE_ID, new org.apache.thrift.meta_data.FieldMetaData("searchEngineId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SEARCH_TYPE, new org.apache.thrift.meta_data.FieldMetaData("searchType", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SearchEngineParam.class, metaDataMap);
  }

  public SearchEngineParam() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SearchEngineParam(SearchEngineParam other) {
    __isset_bitfield = other.__isset_bitfield;
    this.searchEngineId = other.searchEngineId;
    this.searchType = other.searchType;
  }

  public SearchEngineParam deepCopy() {
    return new SearchEngineParam(this);
  }

  @Override
  public void clear() {
    setSearchEngineIdIsSet(false);
    this.searchEngineId = 0;
    setSearchTypeIsSet(false);
    this.searchType = 0;
  }

  public int getSearchEngineId() {
    return this.searchEngineId;
  }

  public SearchEngineParam setSearchEngineId(int searchEngineId) {
    this.searchEngineId = searchEngineId;
    setSearchEngineIdIsSet(true);
    return this;
  }

  public void unsetSearchEngineId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SEARCHENGINEID_ISSET_ID);
  }

  /** Returns true if field searchEngineId is set (has been assigned a value) and false otherwise */
  public boolean isSetSearchEngineId() {
    return EncodingUtils.testBit(__isset_bitfield, __SEARCHENGINEID_ISSET_ID);
  }

  public void setSearchEngineIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SEARCHENGINEID_ISSET_ID, value);
  }

  public int getSearchType() {
    return this.searchType;
  }

  public SearchEngineParam setSearchType(int searchType) {
    this.searchType = searchType;
    setSearchTypeIsSet(true);
    return this;
  }

  public void unsetSearchType() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SEARCHTYPE_ISSET_ID);
  }

  /** Returns true if field searchType is set (has been assigned a value) and false otherwise */
  public boolean isSetSearchType() {
    return EncodingUtils.testBit(__isset_bitfield, __SEARCHTYPE_ISSET_ID);
  }

  public void setSearchTypeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SEARCHTYPE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SEARCH_ENGINE_ID:
      if (value == null) {
        unsetSearchEngineId();
      } else {
        setSearchEngineId((Integer)value);
      }
      break;

    case SEARCH_TYPE:
      if (value == null) {
        unsetSearchType();
      } else {
        setSearchType((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SEARCH_ENGINE_ID:
      return Integer.valueOf(getSearchEngineId());

    case SEARCH_TYPE:
      return Integer.valueOf(getSearchType());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SEARCH_ENGINE_ID:
      return isSetSearchEngineId();
    case SEARCH_TYPE:
      return isSetSearchType();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SearchEngineParam)
      return this.equals((SearchEngineParam)that);
    return false;
  }

  public boolean equals(SearchEngineParam that) {
    if (that == null)
      return false;

    boolean this_present_searchEngineId = true && this.isSetSearchEngineId();
    boolean that_present_searchEngineId = true && that.isSetSearchEngineId();
    if (this_present_searchEngineId || that_present_searchEngineId) {
      if (!(this_present_searchEngineId && that_present_searchEngineId))
        return false;
      if (this.searchEngineId != that.searchEngineId)
        return false;
    }

    boolean this_present_searchType = true && this.isSetSearchType();
    boolean that_present_searchType = true && that.isSetSearchType();
    if (this_present_searchType || that_present_searchType) {
      if (!(this_present_searchType && that_present_searchType))
        return false;
      if (this.searchType != that.searchType)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(SearchEngineParam other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetSearchEngineId()).compareTo(other.isSetSearchEngineId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSearchEngineId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.searchEngineId, other.searchEngineId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSearchType()).compareTo(other.isSetSearchType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSearchType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.searchType, other.searchType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SearchEngineParam(");
    boolean first = true;

    if (isSetSearchEngineId()) {
      sb.append("searchEngineId:");
      sb.append(this.searchEngineId);
      first = false;
    }
    if (isSetSearchType()) {
      if (!first) sb.append(", ");
      sb.append("searchType:");
      sb.append(this.searchType);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SearchEngineParamStandardSchemeFactory implements SchemeFactory {
    public SearchEngineParamStandardScheme getScheme() {
      return new SearchEngineParamStandardScheme();
    }
  }

  private static class SearchEngineParamStandardScheme extends StandardScheme<SearchEngineParam> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SearchEngineParam struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SEARCH_ENGINE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.searchEngineId = iprot.readI32();
              struct.setSearchEngineIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SEARCH_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.searchType = iprot.readI32();
              struct.setSearchTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SearchEngineParam struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetSearchEngineId()) {
        oprot.writeFieldBegin(SEARCH_ENGINE_ID_FIELD_DESC);
        oprot.writeI32(struct.searchEngineId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetSearchType()) {
        oprot.writeFieldBegin(SEARCH_TYPE_FIELD_DESC);
        oprot.writeI32(struct.searchType);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SearchEngineParamTupleSchemeFactory implements SchemeFactory {
    public SearchEngineParamTupleScheme getScheme() {
      return new SearchEngineParamTupleScheme();
    }
  }

  private static class SearchEngineParamTupleScheme extends TupleScheme<SearchEngineParam> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SearchEngineParam struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetSearchEngineId()) {
        optionals.set(0);
      }
      if (struct.isSetSearchType()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetSearchEngineId()) {
        oprot.writeI32(struct.searchEngineId);
      }
      if (struct.isSetSearchType()) {
        oprot.writeI32(struct.searchType);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SearchEngineParam struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.searchEngineId = iprot.readI32();
        struct.setSearchEngineIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.searchType = iprot.readI32();
        struct.setSearchTypeIsSet(true);
      }
    }
  }

}

